### ISSUE TITLE
Remove Preview button when adding new content

### ISSUE THREAD

**Issue by jessica-zivtech** [zivtech/bear#104]
Remove the "Preview" button found at the bottom of the add new content form. This applies to Bear 8 only, as this button has already been removed form Bear 7.

![image](https://cloud.githubusercontent.com/assets/13837270/12898951/29693852-ce7d-11e5-9216-a2b0651d5a11.png)

**Comment by jhoscar1** [comment]
@jessica-zivtech https://github.com/zivtech/bear/pull/106

**Comment by jessica-zivtech** [comment]
PR #106 has been QA'd and is ready for code review. Closing issue.
