### ISSUE TITLE
Missing the "View | Edit | Delete | Devel" tabs when viewing content in admin panel

### ISSUE THREAD

**Issue by jessica-zivtech** [zivtech/bear#107]
**Issue:**
When I am logged in the admin panel and I view published content, I should see the tabs above the content preview for "View", "Edit", "Delete" and "Devel" (I believe this module is enabled by default). Currently they are missing in D8 Bear installations on the view page, but are present on the edit form. These should be visible when viewing created nodes and users.

**Example of tabs (taken from a non-bear sandbox site):**
![image](https://cloud.githubusercontent.com/assets/13837270/13095037/e28b9478-d4dc-11e5-91fe-d2eab0d95a2e.png)

**Missing tabs in Bear D8:**
![image](https://cloud.githubusercontent.com/assets/13837270/13094995/8654107c-d4dc-11e5-9096-d657741db64f.png)

**Comment by alioso** [comment]
I pushed a branch here https://github.com/zivtech/bear/pull/112 but it is broken atm. Will need to wait for a fix before we can review I guess

**Comment by alioso** [comment]
All set, the block config in bear was missing the local task block:

https://240e8041-74cf-4d7d-9ef2-d1bf1a6289d7--pr-112.probo.build/node/1

user: admin
pass: hu7wd4K7nL

**Comment by jessica-zivtech** [comment]
This has been merged. Closing.
