### ISSUE TITLE
Fix multiple field widget so certain field types are orderable

### ISSUE THREAD

**Issue by jessica-zivtech** [zivtech/bear#111]
**Background:**
There is a [patch](https://www.drupal.org/node/2264739#comment-10465641) applied to Bear 7 and 8 that allows site builders the option of making multiple field (unlimited) widgets unorderable. This is controlled with an "Orderable" checkbox on the add new field form. It is checked by default, allowing content creators the ability to drag and drop fields as such:
![image](https://cloud.githubusercontent.com/assets/13837270/13156624/5c049e06-d651-11e5-9306-33a1edc4d648.png)
If it is unchecked, then the fields would look like this:
![image](https://cloud.githubusercontent.com/assets/13837270/13156646/81ae4b48-d651-11e5-917f-6fb33325eb4c.png)

When the [paragraphs module](https://www.drupal.org/project/paragraphs) is enabled, I can make a new field using the paragraphs widget type, and in non-Bear drupal 8 sites, I can add as many paragraph types to the content and they are all orderable. Please note that the [Entity reference revision module](https://www.drupal.org/project/entity_reference_revisions) is a dependency of the paragraphs module in D8.
![image](https://cloud.githubusercontent.com/assets/13837270/13156693/cfe5cdae-d651-11e5-9d4c-d24ebbbbc31a.png)

However in D8 Bear, when I do the same, I am unable to reorder, even when the "Orderable" checkbox is checked.
![image](https://cloud.githubusercontent.com/assets/13837270/13156732/f6d8bde0-d651-11e5-9103-19c54c88d9d9.png)

I am also unable to reorder multiple field widgets for field types **Image** and **File**. 

**Issue to be addressed:**
All field types with an unlimited number of values should be orderable (drag and drop) when the "Orderable" checkbox is marked.

**Comment by grndlvl** [comment]
https://github.com/zivtech/bear/pull/123

**Comment by jessica-zivtech** [comment]
PR was merged, closing.
