### ISSUE TITLE
Prevent inline styling when copying and pasting text into WYSIWYG

### ISSUE THREAD

**Issue by jessica-zivtech** [zivtech/bear#113]
If I copy and paste text from a document or website into a drupal WYSIWYG field set on **Filtered** HTML, it includes the styling from the original text source. Please modify the WYSIWYG to prevent external styling from being included in the code.

Also add `<div>` to the allowed HTML tags in Filtered.

Note: This is definitely happening on D7, and D8 is also a little wonky as well. Please use your discretion to fix if you think this is an issue on D8 as well.

**Comment by alioso** [comment]
All set https://github.com/zivtech/bear/pull/121

**Comment by jessica-zivtech** [comment]
Tested. Closing.
