### ISSUE TITLE
Install the Accessibility Checker plugin

### ISSUE THREAD

**Issue by jessica-zivtech** [zivtech/bear#118]
https://cksource.com/a11ychecker/demo/index.html

"Accessibility Checker is an innovative solution that lets you inspect accessibility level of content created in CKEditor and immediately solve any issues that are found."

Install on D7 and possibly D8 if it allows.

**Comment by alioso** [comment]
All set: https://github.com/zivtech/bear/pull/121

**Comment by jessica-zivtech** [comment]
Per Alban, not able to install on our ckeditor versions.
