### ISSUE TITLE
Look into bear security modules.

### ISSUE THREAD

**Issue by sk33lz** [zivtech/bear#129]
Jody found [this post](https://www.vardot.com/blog/5-security-modules-every-drupal-website-must-have-571?utm_content=buffere8d11&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) which had some good suggestions. I've put together a larger list based on some additional digging I did.
## Possible Bear Security Modules
1. [password_policy](https://www.drupal.org/project/password_policy)
2. [seckit](https://www.drupal.org/project/seckit)
3. [security_review](https://www.drupal.org/project/security_review)
4. [username_enumeration_prevention](https://www.drupal.org/project/username_enumeration_prevention)
5. [genpass](https://www.drupal.org/project/genpass)
6. [remove_generator](https://www.drupal.org/project/remove_generator)
7. [clear_password_field](https://www.drupal.org/project/clear_password_field)
8. [hide_php_fatal_error](https://www.drupal.org/project/hide_php_fatal_error)
9. [login_security](https://www.drupal.org/project/login_security)
10. [autologout](https://www.drupal.org/project/autologout)
11. [email_confirm](https://www.drupal.org/project/email_confirm)
12. [tfa](https://www.drupal.org/project/tfa)
## Other Projects to Check Out
1. [guardr](https://www.drupal.org/project/guardr)

**Comment by jessica-zivtech** [comment]
Moved to JIRA: https://zivtech.atlassian.net/browse/BEAR-4
