### ISSUE TITLE
Unpublished nodes should show unpublished indicator

### ISSUE THREAD

**Issue by jodyHamilton** [zivtech/bear#135]
When I view an unpublished node there should be a visual indicator that it is unpublished. Don't see one in bear 7.

**Comment by alioso** [comment]
All set. https://github.com/zivtech/bear_skin/commit/217de7595ecd11a71005315160795c842c83559d

**Comment by jessica-zivtech** [comment]
Unpublished nodes have a light red background in the body copy to denote it is unpublished:

![image](https://cloud.githubusercontent.com/assets/13837270/14081255/d1ddb230-f4d7-11e5-866b-0549b3427cfd.png)

**Comment by jessica-zivtech** [comment]
Moved to JIRA: https://zivtech.atlassian.net/projects/BEAR/issues/BEAR-2?filter=allopenissues
