### ISSUE TITLE
Add pause/wait step to FeatureContext.php

### ISSUE THREAD

**Issue by jkaeser** [zivtech/bear#98]
Our Behat tests are sometimes running a step faster than Drupal can load a page. When this happens, Behat checks for something that hasn't yet loaded and consequently the test fails. We can prevent this from happening on problem-steps by inserting a step that tells Behat to wait for a second.

We need to add this functionality in Bear's FeatureContext.php file, then use the new step in ContentCreation.feature to prevent the "add a Menu Item" scenario from failing.

**Comment by jkaeser** [comment]
Work done in https://github.com/zivtech/bear/pull/99 is pending review.

**Comment by jessica-zivtech** [comment]
The PR has been merged. Closing Issue.
